package sound;

public enum ClipName {
	MENU,BUTTON_LEVEL1,BUTTON_LEVEL2,BUTTON_LEVEL3, BUTTON_EXIT, PLAYER_DIED, FOOTSTEPS_LEVEL3, MUSIC_LEVEL3, VOCAL_OH, MONSTER_DIED, MUSIC_LEVEL2, MUSIC_LEVEL1, SOUND_EFFECT_BUNUS, SOUND_EFFECT_PRINCESS, PLAYER_WON
}
